baseURL = 'http://tervingo.com/keltivai'
languageCode = 'en-us'
title = 'Keltivai'
theme = 'relearn'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Al-amyr aS-Sagyr (árabe)"
    url = "keltivai/al-amyr-as-sagyr"
    weight = 1