baseURL = 'https://tervingo.com/keltivas/'
locale = 'en-us'
title = 'Keltivas'
theme = 'relearn'

[params.author]
  name = 'Keltivas'
  email = 'info@tervingo.com'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

